jitter=1E-10

random.range=10000
random.spacing=1E-8

#exports eu.scattering.core.design.main.algebra.engine.base.point
#exports eu.scattering.core.design.main.algebra.engine.base.vector
#exports eu.scattering.core.design.main.algebra.engine.extension.line
#exports eu.scattering.core.design.main.algebra.engine.extension.plane
#exports eu.scattering.core.design.main.algebra.engine.shape.ball
#exports eu.scattering.core.design.main.algebra.type.complex
#exports eu.scattering.core.design.main.algebra.type.quaternion
#exports eu.scattering.core.design.main.box.position
#exports eu.scattering.core.design.main.box.rotation
#exports eu.scattering.core.design.support.helper
#exports eu.scattering.core.design