plugins {
    id 'java'
}

def rootProperties = new Properties()
file('../../gradle.properties').withInputStream { rootProperties.load(it) }

def targetGroup = rootProperties.getProperty('group')
def targetVersion = rootProperties.getProperty('version')

group = "${targetGroup}.example"
version = targetVersion

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

boolean isProdTest = gradle.startParameter.taskNames.any { it.contains('javaPackageTestPublished') }

repositories {
    if (!isProdTest) {
        mavenLocal()
    }
    mavenCentral()
}

dependencies {
    implementation "${targetGroup}:eu.scattering.core.lib:${targetVersion}"
    implementation "${targetGroup}:eu.scattering.core.design:${targetVersion}"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

// --- Remote / Java ---

tasks.register('packageTest') {
    description = 'Runs tests against the locally installed package.'
    group = 'remote'

    dependsOn 'clean', 'test'
}

tasks.register('packageTestPublished') {
    description = 'Runs tests against the package from the Maven Central repository.'
    group = 'remote'

    dependsOn 'clean', 'test'
}

// --- Clean ---

tasks.named('clean') {

    delete 'out'
}