jitter=1E-10

random.range=10000
random.spacing=1E-8

#exports eu.scattering.core.design.main.mutable.geometry.base.point
#exports eu.scattering.core.design.main.mutable.geometry.base.vector
#exports eu.scattering.core.design.main.mutable.geometry.extension.line
#exports eu.scattering.core.design.main.mutable.geometry.extension.plane
#exports eu.scattering.core.design.main.mutable.geometry.shape.ball
#exports eu.scattering.core.design.main.mutable.number.complex
#exports eu.scattering.core.design.main.mutable.number.quaternion
#exports eu.scattering.core.design.main.fixed.position
#exports eu.scattering.core.design.main.fixed.rotation
#exports eu.scattering.core.design.support.helper
#exports eu.scattering.core.design


# Divide implementations (default/development) - modules / tests

# number / geometry