package eu.scattering.cli.type;

public enum TYPE_METRIC {
    np,
    rp, rp__avg, rp__std, rp__max, rp__min,
    conn, conn_pt, conn_non_ov,
    ov_p_vol, ov_p_vol__avg, ov_p_vol__std, ov_p_vol__max, ov_p_vol__min,
    ov_p_num, ov_p_num__avg, ov_p_num__std, ov_p_num__max, ov_p_num__min,
    ov_p_lin, ov_p_lin__avg, ov_p_lin__std, ov_p_lin__max, ov_p_lin__min,
    ov_c_vol,
    box, diam,
    len_x, len_y, len_z,
    r_cm_mono, r_cm_poly, r_cm_mesh, r_cm_adapt,
    r_cs,
    r_cb,
    cm_mono, cm_poly, cm_mesh, cm_adapt,
    cs,
    cb,
    vol_sum, vol_mesh, vol_adapt,
    srf_sum, srf_mesh, srf_adapt,
    r_vol_sum, r_vol_mesh, r_vol_adapt,
    r_srf_sum, r_srf_mesh, r_srf_adapt,
    rg_mesh,
    rg_mono, rg_mono_06r1, rg_mono_10r2,
    rg_poly, rg_poly_06r1, rg_poly_10r2,
    angle, angle__fun, angle__avg, angle__std, angle__max, angle__min,
    coord, coord__fun, coord__avg, coord__std, coord__max, coord__min,
    dist, dist__fun, dist__avg, dist__std, dist__max, dist__min,
    df_bc, df_mr, df_dc,
}
