package eu.scattering.cli.type;

public enum TYPE_METRIC {
    NP,
    RP, RP__AVG, RP__STD, RP__MAX, RP__MIN,
    LX,
    LY,
    LZ,
    V_A, V_S, V_C,
    RV_A, RV_S, RV_C,
    S_A, S_S, S_C,
    RS_A, RS_S, RS_C,
    CM_A, CM_SM, CM_SP, CM_C,
    CB,
    CS,
    RCM_A, RCM_SM, RCM_SP, RCM_C,
    RCB,
    RCS,
    RG_SM, RG_SM_06R1, RG_SM_10R2, RG_SP, RG_SP_06R1, RG_SP_10R2, RG_C, RG_D_F,
    DFB,
    DFC,
    OF_CV,
    OF_PV, OF_PV__AVG, OF_PV__STD, OF_PV__MAX, OF_PV__MIN,
    OF_PQ, OF_PQ__AVG, OF_PQ__STD, OF_PQ__MAX, OF_PQ__MIN,
    OF_PL, OF_PL__AVG, OF_PL__STD, OF_PL__MAX, OF_PL__MIN,
    IC,
    IPC,
    INO,
    TA, TA__F, TA__AVG, TA__STD, TA__MAX, TA__MIN,
    PD, PD__F, PD__AVG, PD__STD, PD__MAX, PD__MIN,
    CN, CN__F, CN__AVG, CN__STD, CN__MAX, CN__MIN,
    BC__F,
    DC__F
}
